name: Build ThunderScans Extension

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout Mihon extensions
        uses: actions/checkout@v4
        with:
          repository: mihonapp/extensions
          path: mihon-extensions

      - name: Copy extension into extensions repo
        run: |
          mkdir -p mihon-extensions/src/en
          cp -R src/en/thunderscans mihon-extensions/src/en/

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build extension
        working-directory: mihon-extensions
        run: ./gradlew :src:en:thunderscans:assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: thunder-scans-apk
          path: mihon-extensions/src/en/thunderscans/build/outputs/apk/release/*.apk
          
