name: Build ThunderScans Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Clone Mihon extensions
        run: git clone --depth 1 https://github.com/mihonapp/extensions.git mihon-extensions

      - name: Copy extension into extensions repo
        run: |
          mkdir -p mihon-extensions/src/en
          cp -R src/en/thunderscans mihon-extensions/src/en/

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build extension
        working-directory: mihon-extensions
        run: ./gradlew :src:en:thunderscans:assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: thunder-scans-apk
          path: mihon-extensions/src/en/thunderscans/build/outputs/apk/release/*.apk
          
